version: "3.8"

services:
  web:
    # Remove the platform specification since we're now using native ARM64
    # platform: linux/amd64
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/app/app
      - ./helpers:/app/helpers
      - ./config.py:/app/config.py
      - ./.env:/app/.env
    command: bash -c "python -m uvicorn app.main:app --host 0.0.0.0 --port 80 --reload --env-file /app/.env"
    environment:
      - PYTHONPATH=/app:/app/app
